/* Read public BOT quote snapshots. No order data is sent to the rate provider. */
'use strict';
(function(root){
 const endpoints=['https://cdn.jsdelivr.net/gh/haotool/app@data/public/rates/v3/','https://raw.githubusercontent.com/haotool/app/data/public/rates/v3/'];
 function ceilToCents(raw){if(typeof raw!=='string'||!/^\d{1,3}(?:\.\d{1,12})?$/.test(raw))throw Error('Invalid rate');const [whole,frac='']=raw.split('.');const scale=10n**BigInt(frac.length);const n=BigInt(whole+frac);if(n<=0n||n>=scale)throw Error('Unexpected JPY rate');const cents=(n*100n+scale-1n)/scale;return (cents/100n).toString()+'.'+(cents%100n).toString().padStart(2,'0')}
 async function request(url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const r=await fetch(url,{signal:controller.signal,cache:'no-cache',credentials:'omit',referrerPolicy:'no-referrer'});if(!r.ok)throw Error('HTTP '+r.status);return await r.arrayBuffer()}finally{clearTimeout(timer)}}
 async function object(base,ref,kind){if(!ref||!new RegExp('^'+kind+'/[a-f0-9]{64}\\.json$').test(ref.path)||! /^[a-f0-9]{64}$/.test(ref.sha256))throw Error('Invalid snapshot reference');const bytes=await request(base+ref.path);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),n=>n.toString(16).padStart(2,'0')).join('');if(hash!==ref.sha256)throw Error('Snapshot checksum mismatch');return JSON.parse(new TextDecoder().decode(bytes))}
 async function readProvider(base){const pointer=JSON.parse(new TextDecoder().decode(await request(base+'current.json')));if(pointer.schemaVersion!=='3.0')throw Error('Unsupported rate schema');const manifest=await object(base,pointer.manifest,'releases');const provider=manifest.providers?.find(p=>p.providerId==='bot');if(!provider||provider.checkStatus!=='ok')throw Error('BOT source check failed');const checked=Date.parse(provider.lastSuccessfulCheckAt);if(!Number.isFinite(checked)||Date.now()-checked>24*3600000||checked-Date.now()>10*60000)throw Error('Rate source check is outdated');const snapshot=await object(base,provider.snapshot,'objects');if(snapshot.providerId!=='bot')throw Error('Unexpected provider');const q=snapshot.quotes?.find(q=>q.providerId==='bot'&&q.fromCurrency==='TWD'&&q.toCurrency==='JPY'&&q.status==='available'&&q.sourceQuote?.deliveryMethod==='cash'&&q.sourceQuote?.originalSellField==='cash.sell'&&q.sourceQuote?.subjectCurrency==='JPY'&&q.sourceQuote?.priceCurrency==='TWD'&&q.sourceQuote?.unitAmount==='1');if(!q)throw Error('JPY cash sell quote unavailable');const raw=q.sourceQuote.providerSellPrice;const published=q.sourceQuote.sourcePublishedAt;if(!Number.isFinite(Date.parse(published)))throw Error('Missing source time');return {rate:ceilToCents(raw),raw,publishedAt:published,checkedAt:provider.lastSuccessfulCheckAt,obtainedAt:new Date().toISOString(),source:'臺灣銀行日圓現金賣出',publisher:'RateWise',releaseId:pointer.releaseId}}
 async function getQuote(){let error;for(const base of endpoints){try{return await readProvider(base)}catch(e){error=e}}throw error||Error('Rate unavailable')}
 root.RateSource={getQuote,ceilToCents};
})(typeof window==='undefined'?globalThis:window);
